"""
Maps an existing AI Strategy Center recommendation (already generated by
src/agents/strategy_agent.py and validated by src/orchestration/nodes.py)
into a concrete Commerce Action.

This is a pure, deterministic function — no LLM call happens here. The
commerce action is directly and traceably derived from the recommendation
the merchant selected in the UI; nothing is invented.
"""

from __future__ import annotations

from typing import Any, Dict

from src.commerce.razorpay_client import FIXED_TEST_AMOUNT_INR


def build_commerce_action(recommendation: Dict[str, Any], source_section: str) -> Dict[str, Any]:
    """
    Args:
        recommendation: one item dict from strategy_report (e.g. an entry
            from revenue_opportunities / recommended_actions), exactly as
            produced by the existing Strategy Agent.
        source_section: which report section this came from (kept for the
            audit trail), e.g. "revenue_opportunities".

    Returns:
        A CommerceAction dict: {title, reason, supporting_metric,
        estimated_impact, policy_reference, amount_inr, description,
        source_section}.

    The amount is ALWAYS the fixed ₹499 test amount (FIXED_TEST_AMOUNT_INR)
    — never derived from the LLM's free-text "estimated_impact", since that
    text is a business-impact hypothesis, not a real transaction figure.
    """
    title = (
        recommendation.get("title")
        or recommendation.get("action")
        or "AI-recommended growth action"
    )
    reason = recommendation.get("description") or recommendation.get("rationale") or ""

    description = f"Agentic Commerce Growth Copilot — {title}"[:2048]

    return {
        "title": title,
        "reason": reason,
        "supporting_metric": recommendation.get("supporting_metric") or "",
        "estimated_impact": recommendation.get("estimated_impact"),
        "policy_reference": recommendation.get("policy_reference"),
        "amount_inr": FIXED_TEST_AMOUNT_INR,
        "description": description,
        "source_section": source_section,
    }
